import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db = new PGlite();
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$; grant usage on schema auth to authenticated,anon,service_role;`);
await db.exec(await readFile(new URL('../supabase/migrations/202609090001_portal.sql',import.meta.url),'utf8'));
const owner='00000000-0000-0000-0000-000000000001', a='00000000-0000-0000-0000-000000000002', b='00000000-0000-0000-0000-000000000003';
await db.query('insert into auth.users values ($1),($2),($3)',[owner,a,b]);
await db.query('insert into nsp_admins values ($1)',[owner]);
async function as(id){await db.exec('reset role; set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);}
async function value(sql,args=[]){return Object.values((await db.query(sql,args)).rows[0])[0];}
await as(owner);
const p=await value("select nsp_save_partner(null,'Partner A','a@example.com','ALPHA','active',1000,'10% of net merchandise; refunds deducted',0)");
const p2=await value("select nsp_save_partner(null,'Partner B','b@example.com','BRAVO','active',1000,'10%',0)");
await db.exec('reset role'); await db.query('update nsp_partners set user_id=$1 where id=$2',[a,p]);await db.query('update nsp_partners set user_id=$1 where id=$2',[b,p2]);
await as(owner);
const o=await value("select nsp_record_order($1,'payment-1','Product',10000,now())",[p]);
await assert.rejects(()=>value("select nsp_record_order($1,'payment-1','Product',10000,now())",[p]));
await db.query("select nsp_refund($1,3000,'refund-1')",[o]);await db.query('select nsp_approve($1)',[p]);
await assert.rejects(()=>db.query("select nsp_record_payout($1,701,'payout-bad')",[p]));
await db.query("select nsp_record_payout($1,700,'payout-1')",[p]);
await db.query("select nsp_refund($1,5000,'refund-2')",[o]);
await value("select nsp_record_order($1,'payment-2','Product',10000,now())",[p]);await db.query('select nsp_approve($1)',[p]);
await db.query("select nsp_record_payout($1,800,'payout-2')",[p]);
await as(a); const summary=await value('select nsp_partner_summary()');
assert.equal(summary.orders.length,2); assert.equal(summary.payouts.reduce((s,x)=>s+x.amount_cents,0),1500);
assert(!JSON.stringify(summary).includes('payment-1'));assert(!JSON.stringify(summary).includes('payout-1'));
assert.equal((await db.query('select * from nsp_orders')).rows.length,0);
await assert.rejects(()=>db.query('select nsp_approve($1)',[p]));
await assert.rejects(()=>db.query("update nsp_partners set rate_bps=5000 where id=$1",[p]));
await as(b);assert.equal((await value('select nsp_partner_summary()')).orders.length,0);
assert.equal((await db.query('select * from nsp_commissions')).rows.length,0);
await db.exec('reset role; set role anon');await assert.rejects(()=>db.query('select * from nsp_partners'));await assert.rejects(()=>db.query('select nsp_partner_summary()'));
await db.exec('reset role; set role service_role');
const request={id:'00000000-0000-0000-0000-000000000004',kind:'coa',name:'Test',email:'test@example.com',message:'COA please',referral_code:'ALPHA'};
await db.query('select nsp_submit($1,$2)',[request,'test']);await db.query('select nsp_submit($1,$2)',[request,'test']);
assert.equal(await value('select count(*)::int from nsp_requests'),1);
assert.equal(await value('select partner_id from nsp_requests'),p);
await db.exec('reset role');await db.query("update nsp_partners set status='suspended' where id=$1",[p]);await as(a);await assert.rejects(()=>db.query('select nsp_partner_summary()'));
await db.close();console.log('PASS: migration, role isolation, owner-only mutations, deduplication, referral attribution, refunds, payout reconciliation, suspended access.');
