/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AmbassadorRouteImport } from './routes/ambassador'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminAmbassadorsRouteImport } from './routes/admin.ambassadors'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as PartnerDashboardRouteImport } from './routes/partner.dashboard'
import { Route as PartnerLoginRouteImport } from './routes/partner.login'
import { Route as PartnerResetRouteImport } from './routes/partner.reset'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AmbassadorDashboardRouteImport } from './routes/ambassador.dashboard'
import { Route as AmbassadorLoginRouteImport } from './routes/ambassador.login'
import { Route as AmbassadorResetRouteImport } from './routes/ambassador.reset'
import { Route as AmbassadorIndexRouteImport } from './routes/ambassador.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorRoute = AmbassadorRouteImport.update({
  id: '/ambassador',
  path: '/ambassador',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAmbassadorsRoute = AdminAmbassadorsRouteImport.update({
  id: '/admin/ambassadors',
  path: '/admin/ambassadors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/admin/partners',
  path: '/admin/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerDashboardRoute = PartnerDashboardRouteImport.update({
  id: '/partner/dashboard',
  path: '/partner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerLoginRoute = PartnerLoginRouteImport.update({
  id: '/partner/login',
  path: '/partner/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerResetRoute = PartnerResetRouteImport.update({
  id: '/partner/reset',
  path: '/partner/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorDashboardRoute = AmbassadorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AmbassadorRoute,
} as any)
const AmbassadorLoginRoute = AmbassadorLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AmbassadorRoute,
} as any)
const AmbassadorResetRoute = AmbassadorResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AmbassadorRoute,
} as any)
const AmbassadorIndexRoute = AmbassadorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AmbassadorRoute,
} as any)

interface AmbassadorRouteChildren {
  AmbassadorDashboardRoute: typeof AmbassadorDashboardRoute
  AmbassadorLoginRoute: typeof AmbassadorLoginRoute
  AmbassadorResetRoute: typeof AmbassadorResetRoute
  AmbassadorIndexRoute: typeof AmbassadorIndexRoute
}

const AmbassadorRouteChildren: AmbassadorRouteChildren = {
  AmbassadorDashboardRoute: AmbassadorDashboardRoute,
  AmbassadorLoginRoute: AmbassadorLoginRoute,
  AmbassadorResetRoute: AmbassadorResetRoute,
  AmbassadorIndexRoute: AmbassadorIndexRoute,
}

const AmbassadorRouteWithChildren = AmbassadorRoute._addFileChildren(
  AmbassadorRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ambassador': typeof AmbassadorRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/quality': typeof QualityRoute
  '/owner': typeof OwnerRoute
  '/r/$code': typeof RCodeRoute
  '/terms': typeof TermsRoute
  '/admin/ambassadors': typeof AdminAmbassadorsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/partner/login': typeof PartnerLoginRoute
  '/partner/reset': typeof PartnerResetRoute
  '/product/$slug': typeof ProductSlugRoute
  '/ambassador/dashboard': typeof AmbassadorDashboardRoute
  '/ambassador/login': typeof AmbassadorLoginRoute
  '/ambassador/reset': typeof AmbassadorResetRoute
  '/ambassador/': typeof AmbassadorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/quality': typeof QualityRoute
  '/owner': typeof OwnerRoute
  '/r/$code': typeof RCodeRoute
  '/terms': typeof TermsRoute
  '/admin/ambassadors': typeof AdminAmbassadorsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/partner/login': typeof PartnerLoginRoute
  '/partner/reset': typeof PartnerResetRoute
  '/product/$slug': typeof ProductSlugRoute
  '/ambassador/dashboard': typeof AmbassadorDashboardRoute
  '/ambassador/login': typeof AmbassadorLoginRoute
  '/ambassador/reset': typeof AmbassadorResetRoute
  '/ambassador': typeof AmbassadorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ambassador': typeof AmbassadorRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/quality': typeof QualityRoute
  '/owner': typeof OwnerRoute
  '/r/$code': typeof RCodeRoute
  '/terms': typeof TermsRoute
  '/admin/ambassadors': typeof AdminAmbassadorsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/partner/login': typeof PartnerLoginRoute
  '/partner/reset': typeof PartnerResetRoute
  '/product/$slug': typeof ProductSlugRoute
  '/ambassador/dashboard': typeof AmbassadorDashboardRoute
  '/ambassador/login': typeof AmbassadorLoginRoute
  '/ambassador/reset': typeof AmbassadorResetRoute
  '/ambassador/': typeof AmbassadorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ambassador'
    | '/catalog'
    | '/contact'
    | '/privacy'
    | '/quality'
    | '/owner'
    | '/r/$code'
    | '/terms'
    | '/admin/ambassadors'
    | '/admin/partners'
    | '/partner/dashboard'
    | '/partner/login'
    | '/partner/reset'
    | '/product/$slug'
    | '/ambassador/dashboard'
    | '/ambassador/login'
    | '/ambassador/reset'
    | '/ambassador/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/contact'
    | '/privacy'
    | '/quality'
    | '/owner'
    | '/r/$code'
    | '/terms'
    | '/admin/ambassadors'
    | '/admin/partners'
    | '/partner/dashboard'
    | '/partner/login'
    | '/partner/reset'
    | '/product/$slug'
    | '/ambassador/dashboard'
    | '/ambassador/login'
    | '/ambassador/reset'
    | '/ambassador'
  id:
    | '__root__'
    | '/'
    | '/ambassador'
    | '/catalog'
    | '/contact'
    | '/privacy'
    | '/quality'
    | '/owner'
    | '/r/$code'
    | '/terms'
    | '/admin/ambassadors'
    | '/admin/partners'
    | '/partner/dashboard'
    | '/partner/login'
    | '/partner/reset'
    | '/product/$slug'
    | '/ambassador/dashboard'
    | '/ambassador/login'
    | '/ambassador/reset'
    | '/ambassador/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmbassadorRoute: typeof AmbassadorRouteWithChildren
  CatalogRoute: typeof CatalogRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  QualityRoute: typeof QualityRoute
  OwnerRoute: typeof OwnerRoute
  RCodeRoute: typeof RCodeRoute
  TermsRoute: typeof TermsRoute
  AdminAmbassadorsRoute: typeof AdminAmbassadorsRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  PartnerDashboardRoute: typeof PartnerDashboardRoute
  PartnerLoginRoute: typeof PartnerLoginRoute
  PartnerResetRoute: typeof PartnerResetRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassador': {
      id: '/ambassador'
      path: '/ambassador'
      fullPath: '/ambassador'
      preLoaderRoute: typeof AmbassadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ambassadors': {
      id: '/admin/ambassadors'
      path: '/admin/ambassadors'
      fullPath: '/admin/ambassadors'
      preLoaderRoute: typeof AdminAmbassadorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/admin/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/dashboard': {
      id: '/partner/dashboard'
      path: '/partner/dashboard'
      fullPath: '/partner/dashboard'
      preLoaderRoute: typeof PartnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/login': {
      id: '/partner/login'
      path: '/partner/login'
      fullPath: '/partner/login'
      preLoaderRoute: typeof PartnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/reset': {
      id: '/partner/reset'
      path: '/partner/reset'
      fullPath: '/partner/reset'
      preLoaderRoute: typeof PartnerResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassador/dashboard': {
      id: '/ambassador/dashboard'
      path: '/dashboard'
      fullPath: '/ambassador/dashboard'
      preLoaderRoute: typeof AmbassadorDashboardRouteImport
      parentRoute: typeof AmbassadorRoute
    }
    '/ambassador/login': {
      id: '/ambassador/login'
      path: '/login'
      fullPath: '/ambassador/login'
      preLoaderRoute: typeof AmbassadorLoginRouteImport
      parentRoute: typeof AmbassadorRoute
    }
    '/ambassador/reset': {
      id: '/ambassador/reset'
      path: '/reset'
      fullPath: '/ambassador/reset'
      preLoaderRoute: typeof AmbassadorResetRouteImport
      parentRoute: typeof AmbassadorRoute
    }
    '/ambassador/': {
      id: '/ambassador/'
      path: '/'
      fullPath: '/ambassador/'
      preLoaderRoute: typeof AmbassadorIndexRouteImport
      parentRoute: typeof AmbassadorRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmbassadorRoute: AmbassadorRouteWithChildren,
  CatalogRoute: CatalogRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  QualityRoute: QualityRoute,
  OwnerRoute: OwnerRoute,
  RCodeRoute: RCodeRoute,
  TermsRoute: TermsRoute,
  AdminAmbassadorsRoute: AdminAmbassadorsRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  PartnerDashboardRoute: PartnerDashboardRoute,
  PartnerLoginRoute: PartnerLoginRoute,
  PartnerResetRoute: PartnerResetRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
